### ISSUE TITLE
Any New Ideas? Yes!!!

### ISSUE THREAD

**Issue by ghost** [MidnightPhantom/Insane_crafts#1]
Noticed in the Forum, your Post.
Here some Ideas.

Marram Grass is not renewable, maybe a recipe like this, like the Ore recipes in this Mod. S = Sand, M = Marram Grass
S S S
S M S
S S S = 8 Marram Grass

default:marram_grass_1
default:sand

Fern is renewable, but only natural. D = Dirt, F = Fern
D D D
D F D
D D D = 8 Fern

default:fern_1
default:dirt

The Corals in general, would be nice, if they would be renewable.
Brown Dye = Br, Orange Dye = O, Coral Skeleton = CS
Br CS Br 
CS CS CS
Br CS Br = 5 Brown Coral

O CS O
CS CS CS
O CS O = 5 Orange Coral

default:coral_skeleton
default:coral_brown
default:coral_orange

Coral Skeleton need pickaxe to be mined, maybe like the Insane Craft recipes for ores, Coral Skeleton in the middle and Stone around it. Stone = St, Coral Skeleton = CS
St St St
St CS St
St St St = 8 Coral Skeleton

default:stone
default:coral_skeleton

For the Coral plants (Rooted Corals), Cyan, Green and Pink Corals, Coral Skeleton around them, in the crafting grid.
Rooted Corals (Cyan, Green, Pink) = RC, Coral Skeleton = CS
CS CS CS
CS RC CS
CS CS CS = 8 (Cyan, Green, Pink) Corals

default:coral_cyan
default:coral_green
default:coral_pink
default:coral_skeleton

Thats all.

**Comment by MidnightPhantom** [comment]
Hey thanks man, but for marram grass I will change the recipe a bit, and will also use recipes from regnum
